version: "3"
services:
  test:
    build: .
    command: develop
    environment:
      MONGO_DATABASE: 'doc-importer-tasks'
      CT_REGISTER_MODE: auto
      CT_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:5000
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      API_VERSION: v1
      FASTLY_ENABLED: "false"
    volumes:
      - ./app:/opt/doc-orchestrator/app
